### ISSUE TITLE
Does image size matters?

### ISSUE THREAD

**Issue by JohnnieXDU** [microsoft/MaskFlownet#2]
Hi, really appreciate for opening the code! Can i have few questions?

Does the image size influence the performance? I mean in the training stage, image patches (**896x320** for Kitti) are used. But in testing, do you still use the image patches? Or use the entire image (around **1240x370** for Kitti)?

I know cropping is for augmentation, but If you use small pates for training, and larger images for testing, does this strategy will influence the performance?

Thank you very much!

**Comment by simon1727** [comment]
Hi Johnnie, thanks for your interest in our work!

To fairly evaluate the overall performance, the entire image is used for testing, and we believe that the image size will influence but not that much. For KITTI dataset, as we discussed in the 5.1 section in the paper, _input images are resized to 1280×576 (before augmentation and cropping) since the decreased aspect ratio better balances the vertical and horizontal displacement_, so, for testing, a similar resize should be applied to keep the aspect ratio the same.

Hope this solve your questions.
